slogo_team07: turtleClasses.TurtleKeyHandler Class Reference
turtleClasses.TurtleKeyHandler Class Reference
Public Member Functions
TurtleKeyHandler (TurtleMover mover, PaneUpdater pu)
void handle (KeyEvent event)
Private Attributes
TurtleMover myMover
PaneUpdater myPaneUpdater
Static Private Attributes
static final Map< KeyCode, String > ARROW_KEYS
Detailed Description
This class represents a key handler for turtles on the screen.
Author
Chris Bernt
Safkat Islam
Definition at line 19 of file TurtleKeyHandler.java.
Constructor & Destructor Documentation
turtleClasses.TurtleKeyHandler.TurtleKeyHandler (TurtleMover mover, PaneUpdater pu)
Constructor.
Parameters
mover The turtle mover.
pu The pane updater.
Definition at line 45 of file TurtleKeyHandler.java.
Member Function Documentation
void turtleClasses.TurtleKeyHandler.handle (KeyEvent event)
Checks whether the key pressed is one with an actual command. If so, calls upon the mover to execute that command.
Definition at line 55 of file TurtleKeyHandler.java.
References turtleClasses.TurtleKeyHandler.ARROW_KEYS, SLogoControllers.InputController.getInstructions(), SLogoControllers.InputController.giveInput(), turtleClasses.TurtleMover.startDrawing(), and frontend.PaneUpdater.updateAll().
Member Data Documentation
final Map<KeyCode, String> turtleClasses.TurtleKeyHandler.ARROW_KEYS static private
Initial value:
= new HashMap<KeyCode, String>()
            {
                private static final long serialVersionUID = 1L;
            {
                put(KeyCode.UP, "fd 50");
                put(KeyCode.DOWN, "fd -50");
                put(KeyCode.LEFT, "left 10");
                put(KeyCode.RIGHT, "right 10");
            }}
Map of keys to their command.
Definition at line 27 of file TurtleKeyHandler.java.
Referenced by turtleClasses.TurtleKeyHandler.handle().
TurtleMover turtleClasses.TurtleKeyHandler.myMover private
Definition at line 21 of file TurtleKeyHandler.java.
PaneUpdater turtleClasses.TurtleKeyHandler.myPaneUpdater private
Definition at line 22 of file TurtleKeyHandler.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team07/repository/src/turtleClasses/TurtleKeyHandler.java