slogo_team07: expressionTree.ExpressionNode Class Reference
expressionTree.ExpressionNode Class Reference abstract
Public Member Functions
ExpressionNode ()
ExpressionNode (int numChild)
abstract double evaluate ()
List< DisplayNode > makeInstructionList ()
void setValue (double a)
double getValue ()
void setChildren (Stack< ExpressionNode > childStack)
Protected Member Functions
ExpressionNode getLeft ()
ExpressionNode getRight ()
void setLeft (ExpressionNode toSet)
void setRight (ExpressionNode toSet)
int getNumChildren ()
Protected Attributes
double myValue
ExpressionNode myRight
ExpressionNode myLeft
int numChildren
List< DisplayNode > instructionList
Detailed Description
Superclass for node representation of all instructions within the expression tree.
Default assumes that Node has two children, as the vast majority of Slogo commands take in either one or two inputs. Those commands that take in greater than two inputs can overwrite the setChildren method in ExpressionNode and add new children variables.
Only evaluate() is abstract. Evaluate() sets the node's value by recursively evaluating its children - this method differs for different types of commands.
Author
Mike Zhu
Definition at line 22 of file ExpressionNode.java.
Constructor & Destructor Documentation
expressionTree.ExpressionNode.ExpressionNode ()
Default number of children is 2. The vast majority of Slogo commands follows this syntax
Definition at line 34 of file ExpressionNode.java.
expressionTree.ExpressionNode.ExpressionNode (int numChild)
Definition at line 38 of file ExpressionNode.java.
Member Function Documentation
abstract double expressionTree.ExpressionNode.evaluate () abstract
Referenced by mathOperations.Sum.evaluate(), mathOperations.Difference.evaluate(), mathOperations.Minus.evaluate(), displayCommands.Forward.evaluate(), displayCommands.Left.evaluate(), mathOperations.Quotient.evaluate(), mathOperations.Remainder.evaluate(), displayCommands.Right.evaluate(), mathOperations.Product.evaluate(), displayCommands.SetPenSize.evaluate(), displayCommands.Backward.evaluate(), controlStructures.If.evaluate(), controlStructures.MakeVariable.evaluate(), displayCommands.AskWith.evaluate(), displayCommands.SetTowards.evaluate(), displayCommands.SetShape.evaluate(), displayCommands.SetBackground.evaluate(), controlStructures.IfElse.evaluate(), controlStructures.DoTimes.evaluate(), controlStructures.Repeat.evaluate(), displayCommands.Tell.evaluate(), displayCommands.SetPenColor.evaluate(), displayCommands.Ask.evaluate(), displayCommands.SetPalette.evaluate(), expressionTree.ExpressionTreeBuilder.getTree(), controlStructures.Repeat.makeInstructionList(), and controlStructures.IfElse.makeInstructionList().
ExpressionNode expressionTree.ExpressionNode.getLeft () protected
Definition at line 67 of file ExpressionNode.java.
References expressionTree.ExpressionNode.myLeft.
Referenced by comparators.Not.evaluate(), mathOperations.Sum.evaluate(), comparators.And.evaluate(), mathOperations.Difference.evaluate(), mathOperations.Minus.evaluate(), comparators.Equal.evaluate(), mathOperations.Quotient.evaluate(), comparators.GreaterThan.evaluate(), comparators.NotEqual.evaluate(), mathOperations.Tangent.evaluate(), comparators.Or.evaluate(), mathOperations.ArcTangent.evaluate(), comparators.LessThan.evaluate(), mathOperations.Log.evaluate(), mathOperations.Sine.evaluate(), mathOperations.Product.evaluate(), mathOperations.Remainder.evaluate(), mathOperations.Cosine.evaluate(), mathOperations.Power.evaluate(), mathOperations.SlogoRandom.evaluate(), controlStructures.DoTimes.evaluate(), controlStructures.Repeat.evaluate(), displayCommands.Tell.evaluate(), controlStructures.DoTimes.makeInstructionList(), controlStructures.Repeat.makeInstructionList(), and expressionTree.ExpressionNode.makeInstructionList().
int expressionTree.ExpressionNode.getNumChildren () protected
Definition at line 89 of file ExpressionNode.java.
References expressionTree.ExpressionNode.numChildren.
Referenced by expressionTree.ExpressionNode.setChildren().
ExpressionNode expressionTree.ExpressionNode.getRight () protected
Definition at line 71 of file ExpressionNode.java.
References expressionTree.ExpressionNode.myRight.
Referenced by mathOperations.Sum.evaluate(), comparators.And.evaluate(), comparators.Equal.evaluate(), comparators.NotEqual.evaluate(), comparators.GreaterThan.evaluate(), comparators.Or.evaluate(), mathOperations.Difference.evaluate(), mathOperations.Quotient.evaluate(), mathOperations.Product.evaluate(), mathOperations.Remainder.evaluate(), comparators.LessThan.evaluate(), mathOperations.Power.evaluate(), controlStructures.DoTimes.evaluate(), controlStructures.Repeat.evaluate(), controlStructures.DoTimes.makeInstructionList(), controlStructures.Repeat.makeInstructionList(), and expressionTree.ExpressionNode.makeInstructionList().
double expressionTree.ExpressionNode.getValue ()
Definition at line 93 of file ExpressionNode.java.
References expressionTree.ExpressionNode.myValue.
Referenced by displayCommands.AskWith.evaluate(), and displayCommands.Ask.evaluate().
List<DisplayNode> expressionTree.ExpressionNode.makeInstructionList ()
Extracts the displayNodes (those nodes sent to the frontend and run to move the turtle) using in-order traversal starting from this node. Thus returns insns in the order that they were typed.
This allows for nested "recursive" instructions.
Returns
Definition at line 52 of file ExpressionNode.java.
References expressionTree.ExpressionNode.getLeft(), expressionTree.ExpressionNode.getRight(), and expressionTree.ExpressionNode.instructionList.
Referenced by controlStructures.IfElse.makeInstructionList().
void expressionTree.ExpressionNode.setChildren (Stack< ExpressionNode > childStack)
Throws error when an EmptyStackException occurs, indicating that user did not follow correct Slogo syntax (likely has too few arguments for a given method)
Parameters
childStack
Definition at line 102 of file ExpressionNode.java.
References expressionTree.ExpressionNode.getNumChildren(), expressionTree.ExpressionNode.setLeft(), and expressionTree.ExpressionNode.setRight().
Referenced by expressionTree.ExpressionTreeBuilder.getTree().
void expressionTree.ExpressionNode.setLeft (ExpressionNode toSet) protected
Definition at line 75 of file ExpressionNode.java.
Referenced by controlStructures.IfElse.setChildren(), and expressionTree.ExpressionNode.setChildren().
void expressionTree.ExpressionNode.setRight (ExpressionNode toSet) protected
Definition at line 80 of file ExpressionNode.java.
Referenced by controlStructures.IfElse.setChildren(), and expressionTree.ExpressionNode.setChildren().
void expressionTree.ExpressionNode.setValue (double a)
Definition at line 85 of file ExpressionNode.java.
Referenced by controlStructures.MakeVariable.evaluate(), and expressionTree.ExpressionNodeFactory.getNode().
Member Data Documentation
List<DisplayNode> expressionTree.ExpressionNode.instructionList protected
Definition at line 28 of file ExpressionNode.java.
Referenced by controlStructures.DoTimes.makeInstructionList(), controlStructures.Repeat.makeInstructionList(), displayCommands.Tell.makeInstructionList(), controlStructures.IfElse.makeInstructionList(), expressionTree.ExpressionNode.makeInstructionList(), and displayCommands.Ask.makeInstructionList().
ExpressionNode expressionTree.ExpressionNode.myLeft protected
Definition at line 25 of file ExpressionNode.java.
Referenced by displayCommands.Forward.evaluate(), displayCommands.Left.evaluate(), displayCommands.Right.evaluate(), displayCommands.SetPenSize.evaluate(), displayCommands.Backward.evaluate(), controlStructures.If.evaluate(), controlStructures.MakeVariable.evaluate(), displayCommands.AskWith.evaluate(), displayCommands.SetTowards.evaluate(), displayCommands.SetShape.evaluate(), displayCommands.SetBackground.evaluate(), controlStructures.IfElse.evaluate(), displayCommands.Tell.evaluate(), displayCommands.SetPenColor.evaluate(), displayCommands.Ask.evaluate(), displayCommands.SetPalette.evaluate(), expressionTree.ExpressionNode.getLeft(), controlStructures.DoTimes.makeInstructionList(), controlStructures.IfElse.makeInstructionList(), and displayCommands.SetPalette.setChildren().
ExpressionNode expressionTree.ExpressionNode.myRight protected
Definition at line 24 of file ExpressionNode.java.
Referenced by controlStructures.If.evaluate(), controlStructures.MakeVariable.evaluate(), displayCommands.AskWith.evaluate(), displayCommands.SetTowards.evaluate(), controlStructures.IfElse.evaluate(), displayCommands.Ask.evaluate(), displayCommands.SetPalette.evaluate(), expressionTree.ExpressionNode.getRight(), controlStructures.IfElse.makeInstructionList(), and displayCommands.SetPalette.setChildren().
double expressionTree.ExpressionNode.myValue protected
Definition at line 23 of file ExpressionNode.java.
Referenced by displayCommands.Backward.doAction(), displayCommands.SetPenSize.doAction(), displayCommands.SetShape.doAction(), displayCommands.SetBackground.doAction(), displayCommands.Forward.doAction(), displayCommands.Left.doAction(), displayCommands.Right.doAction(), displayCommands.SetPenColor.doAction(), mathOperations.Sum.evaluate(), displayCommands.Forward.evaluate(), displayCommands.Left.evaluate(), displayCommands.Right.evaluate(), commandAbstractClasses.Constant.evaluate(), displayCommands.SetPenSize.evaluate(), displayCommands.Backward.evaluate(), controlStructures.If.evaluate(), controlStructures.MakeVariable.evaluate(), displayCommands.AskWith.evaluate(), displayCommands.SetTowards.evaluate(), displayCommands.SetBackground.evaluate(), displayCommands.SetShape.evaluate(), controlStructures.IfElse.evaluate(), expressionTree.VariableNode.evaluate(), displayCommands.Tell.evaluate(), expressionTree.ListNode.evaluate(), displayCommands.SetPenColor.evaluate(), displayCommands.Ask.evaluate(), displayCommands.SetPalette.evaluate(), expressionTree.VariableNode.getValue(), expressionTree.ExpressionNode.getValue(), expressionTree.VariableNode.SetInfo(), and displayCommands.DisplayNode.toString().
int expressionTree.ExpressionNode.numChildren protected
Definition at line 26 of file ExpressionNode.java.
Referenced by expressionTree.ExpressionNode.getNumChildren(), controlStructures.MakeUserInstruction.setChildren(), and controlStructures.IfElse.setMiddle().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team07/repository/src/expressionTree/ExpressionNode.java