slogo_team07: frontend.SLogoCanvas Class Reference
frontend.SLogoCanvas Class Reference
Public Member Functions
SLogoCanvas (double width, double height, double x, double y)
void removeObjects (Object o)
void setUpColorPalette ()
void changeBackground (Color c)
void changeBackground (int index)
void addColor (double index, int r, int g, int b)
Color getColor (int index)
Pane getHolder ()
void toggleGridLines ()
Static Public Attributes
static final Color START_COLOR = Color.web(GUI_PREFERENCES.getString("CanvasBackgroundColor"))
Private Attributes
Pane myHolder
GridPane myGrid
Rectangle myBackground
List< Color > myColors
Static Private Attributes
static final int SPACE_BETWEEN_GRID_LINES = 10
Detailed Description
This class represents the field where the turtle can be and where the lines are drawn.
Author
Chris Bernt
Safkat Islam
Definition at line 23 of file SLogoCanvas.java.
Constructor & Destructor Documentation
frontend.SLogoCanvas.SLogoCanvas (double width, double height, double x, double y)
Constructor.
Parameters
width The width of the drawing area.
height The height of the drawing area.
x The x-Coordinate of the drawing area.
y The y-Coordinate of the drawing area.
Definition at line 41 of file SLogoCanvas.java.
References frontend.SLogoCanvas.setUpColorPalette(), and frontend.SLogoCanvas.SPACE_BETWEEN_GRID_LINES.
Member Function Documentation
void frontend.SLogoCanvas.addColor (double index, int r, int g, int b)
Adds a color specified by the given r,g,b values to this particular index in the color list.
Parameters
index The index at which to add this particular color in the palette.
r The red value 0-255.
g The green value 0-255.
b The blue value 0-255.
Definition at line 136 of file SLogoCanvas.java.
void frontend.SLogoCanvas.changeBackground (Color c)
Changes the canvas's background.
Parameters
c The color to change the background to.
Definition at line 113 of file SLogoCanvas.java.
Referenced by frontend.SLogoCanvas.changeBackground(), and displayCommands.SetBackground.doAction().
void frontend.SLogoCanvas.changeBackground (int index)
Changes the canvas's background.
Parameters
index The index of the palette list from which to grab the color to change the background to.
Definition at line 122 of file SLogoCanvas.java.
References frontend.SLogoCanvas.changeBackground(), and frontend.SLogoCanvas.getColor().
Color frontend.SLogoCanvas.getColor (int index)
Gets the color at the index in the palette.
Parameters
index The index from which to get the color in the palette.
Returns
The color at the given index.
Definition at line 147 of file SLogoCanvas.java.
Referenced by frontend.SLogoCanvas.changeBackground(), and displayCommands.SetPenColor.doAction().
Pane frontend.SLogoCanvas.getHolder ()
Gets the holder (pane) that the canvas is in.
Returns
The pane the canvas is in.
Definition at line 157 of file SLogoCanvas.java.
References frontend.SLogoCanvas.myHolder.
Referenced by frontend.SLogoCanvas.removeObjects(), and frontend.SLogoWorkspace.SLogoWorkspace().
void frontend.SLogoCanvas.removeObjects (Object o)
Removes all objects of this type from the canvas.
Parameters
o The object to represent the type to remove.
Definition at line 83 of file SLogoCanvas.java.
References frontend.SLogoCanvas.getHolder().
Referenced by displayCommands.ClearObjects.doAction().
void frontend.SLogoCanvas.setUpColorPalette ()
Takes the resource bundle and sets up the initial color list to grab from SLogo commands.
Definition at line 96 of file SLogoCanvas.java.
Referenced by frontend.SLogoCanvas.SLogoCanvas().
void frontend.SLogoCanvas.toggleGridLines ()
Toggles whether the grid lines are displayed.
Definition at line 165 of file SLogoCanvas.java.
Member Data Documentation
Rectangle frontend.SLogoCanvas.myBackground private
Definition at line 27 of file SLogoCanvas.java.
List<Color> frontend.SLogoCanvas.myColors private
Definition at line 28 of file SLogoCanvas.java.
GridPane frontend.SLogoCanvas.myGrid private
Definition at line 26 of file SLogoCanvas.java.
Pane frontend.SLogoCanvas.myHolder private
Definition at line 25 of file SLogoCanvas.java.
Referenced by frontend.SLogoCanvas.getHolder().
final int frontend.SLogoCanvas.SPACE_BETWEEN_GRID_LINES = 10 static private
Definition at line 30 of file SLogoCanvas.java.
Referenced by frontend.SLogoCanvas.SLogoCanvas().
final Color frontend.SLogoCanvas.START_COLOR = Color.web(GUI_PREFERENCES.getString("CanvasBackgroundColor")) static
Definition at line 31 of file SLogoCanvas.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team07/repository/src/frontend/SLogoCanvas.java