slogo_team07: turtleClasses.TurtleSnapshot Class Reference
turtleClasses.TurtleSnapshot Class Reference
Public Member Functions
void update (Turtle turtle)
Static Public Member Functions
static TurtleSnapshot getTurtleSnapshot ()
Public Attributes
double xCor
double yCor
double direction
boolean penDown
boolean showing
int id
Private Member Functions
TurtleSnapshot ()
Static Private Attributes
static TurtleSnapshot instance = new TurtleSnapshot()
Detailed Description
Passive singleton representing a snapshot of a turtle's current data that is passed for the backend's queries.
Author
Chris Bernt
Safkat Islam
Definition at line 13 of file TurtleSnapshot.java.
Constructor & Destructor Documentation
turtleClasses.TurtleSnapshot.TurtleSnapshot () private
Constructor, sets up all data.
Parameters
turtle The turtle to copy data from.
Definition at line 27 of file TurtleSnapshot.java.
Member Function Documentation
static TurtleSnapshot turtleClasses.TurtleSnapshot.getTurtleSnapshot () static
Gets a turtle snapshot from the given turtle.
Parameters
turtle The turtle to get information from.
Returns
The turtle snapshot from the given turtle.
Definition at line 36 of file TurtleSnapshot.java.
References turtleClasses.TurtleSnapshot.instance.
Referenced by turtleQueries.ID.evaluate(), turtleQueries.YCoordinate.evaluate(), turtleQueries.IsPenDown.evaluate(), turtleQueries.Heading.evaluate(), turtleQueries.XCoordinate.evaluate(), turtleQueries.IsShowing.evaluate(), and turtleClasses.TurtleMover.startDrawing().
void turtleClasses.TurtleSnapshot.update (Turtle turtle)
Updates the instance of the turtle snapshot.
Parameters
turtle The turtle to get data from.
Definition at line 44 of file TurtleSnapshot.java.
References turtleClasses.Turtle.getDirection(), turtleClasses.Turtle.getID(), turtleClasses.Turtle.getPen(), turtleClasses.Turtle.getX(), turtleClasses.Turtle.getY(), frontend.Pen.isPenDown(), and turtleClasses.Turtle.isShowing().
Referenced by turtleClasses.TurtleMover.startDrawing().
Member Data Documentation
double turtleClasses.TurtleSnapshot.direction
Definition at line 18 of file TurtleSnapshot.java.
Referenced by turtleQueries.Heading.evaluate().
int turtleClasses.TurtleSnapshot.id
Definition at line 21 of file TurtleSnapshot.java.
Referenced by turtleQueries.ID.evaluate().
TurtleSnapshot turtleClasses.TurtleSnapshot.instance = new TurtleSnapshot() static private
Definition at line 15 of file TurtleSnapshot.java.
Referenced by turtleClasses.TurtleSnapshot.getTurtleSnapshot().
boolean turtleClasses.TurtleSnapshot.penDown
Definition at line 19 of file TurtleSnapshot.java.
Referenced by turtleQueries.IsPenDown.evaluate().
boolean turtleClasses.TurtleSnapshot.showing
Definition at line 20 of file TurtleSnapshot.java.
Referenced by turtleQueries.IsShowing.evaluate().
double turtleClasses.TurtleSnapshot.xCor
Definition at line 16 of file TurtleSnapshot.java.
Referenced by turtleQueries.XCoordinate.evaluate().
double turtleClasses.TurtleSnapshot.yCor
Definition at line 17 of file TurtleSnapshot.java.
Referenced by turtleQueries.YCoordinate.evaluate().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team07/repository/src/turtleClasses/TurtleSnapshot.java