slogo_team07: frontend.SLogoWorkspace Class Reference
frontend.SLogoWorkspace Class Reference
Classes
class AddWorkspaceButton
Public Member Functions
SLogoWorkspace (TabPane tp)
Tab createWorkspace (int numTab)
Static Public Attributes
static final int CANVAS_WIDTH = 500
static final int CANVAS_HEIGHT = 500
static final ResourceBundle GUI_PREFERENCES = ResourceBundle.getBundle("resources.buttonLanguages/GUIPreferences")
static final ResourceBundle GUI_NAMES = ResourceBundle.getBundle("resources.buttonLanguages/EnglishButtonNames")
static final String[] IMAGE_LIST = GUI_PREFERENCES.getString("StartingImages").split(",")
Private Attributes
double myWidth
double myHeight
Group myRoot = new Group()
SLogoCanvas myCanvas
ColorPicker myColorPicker = new ColorPicker()
Turtle myInitialTurtle
TurtleMover myMover
List< GUIFeature > startingFeatures
TabPane myTabPane
Translator myTranslator
TurtleCollection myTurtleCollection
PaneUpdater myPaneUpdater
HistoryCollection myHistory
Static Private Attributes
static final int LINE_WIDTH_TEXT_BOX_HEIGHT = 10
static final int CANVAS_OFFSET = 10
static final int PANE_HEIGHT = 100
static final int PANE_WIDTH = 200
static final int TEXT_BOX_WIDTH = 100
Detailed Description
This class represents a workspace with unique elements, including the turtles, and all GUIFeatures. It is added as a tab to the TabPane in the GUIMaker.
Author
Chris Bernt
Safkat Islam
Definition at line 53 of file SLogoWorkspace.java.
Constructor & Destructor Documentation
frontend.SLogoWorkspace.SLogoWorkspace (TabPane tp)
Constructor.
Parameters
tp The TabPane to which to add workspaces.
A List of panes with updateable information.
A List of all of the features to be added statically to the workspace.
Definition at line 86 of file SLogoWorkspace.java.
References turtleClasses.TurtleCollection.addTurtle(), frontend.SLogoWorkspace.CANVAS_OFFSET, frontend.SLogoCanvas.getHolder(), frontend.SLogoWorkspace.myCanvas, frontend.SLogoWorkspace.myColorPicker, frontend.SLogoWorkspace.myHistory, frontend.SLogoWorkspace.myMover, frontend.SLogoWorkspace.myPaneUpdater, frontend.SLogoWorkspace.myTabPane, frontend.SLogoWorkspace.myTranslator, frontend.SLogoWorkspace.myTurtleCollection, and frontend.SLogoWorkspace.TEXT_BOX_WIDTH.
Referenced by frontend.SLogoWorkspace.AddWorkspaceButton.action().
Member Function Documentation
Tab frontend.SLogoWorkspace.createWorkspace (int numTab)
Adds all of the initial GUIFeatures to the workspace.
Parameters
numTab The number of the tab being added.
Returns
The created tab.
Definition at line 158 of file SLogoWorkspace.java.
Referenced by frontend.SLogoWorkspace.AddWorkspaceButton.action(), and frontend.GUIMaker.make().
Member Data Documentation
final int frontend.SLogoWorkspace.CANVAS_HEIGHT = 500 static
Definition at line 61 of file SLogoWorkspace.java.
final int frontend.SLogoWorkspace.CANVAS_OFFSET = 10 static private
Definition at line 56 of file SLogoWorkspace.java.
Referenced by frontend.SLogoWorkspace.SLogoWorkspace().
final int frontend.SLogoWorkspace.CANVAS_WIDTH = 500 static
Definition at line 60 of file SLogoWorkspace.java.
final ResourceBundle frontend.SLogoWorkspace.GUI_NAMES = ResourceBundle.getBundle("resources.buttonLanguages/EnglishButtonNames") static
Definition at line 75 of file SLogoWorkspace.java.
final ResourceBundle frontend.SLogoWorkspace.GUI_PREFERENCES = ResourceBundle.getBundle("resources.buttonLanguages/GUIPreferences") static
Definition at line 74 of file SLogoWorkspace.java.
final String [] frontend.SLogoWorkspace.IMAGE_LIST = GUI_PREFERENCES.getString("StartingImages").split(",") static
Definition at line 76 of file SLogoWorkspace.java.
final int frontend.SLogoWorkspace.LINE_WIDTH_TEXT_BOX_HEIGHT = 10 static private
Definition at line 55 of file SLogoWorkspace.java.
SLogoCanvas frontend.SLogoWorkspace.myCanvas private
Definition at line 65 of file SLogoWorkspace.java.
Referenced by frontend.SLogoWorkspace.SLogoWorkspace().
ColorPicker frontend.SLogoWorkspace.myColorPicker = new ColorPicker() private
Definition at line 66 of file SLogoWorkspace.java.
Referenced by frontend.SLogoWorkspace.SLogoWorkspace().
double frontend.SLogoWorkspace.myHeight private
Definition at line 63 of file SLogoWorkspace.java.
HistoryCollection frontend.SLogoWorkspace.myHistory private
Definition at line 78 of file SLogoWorkspace.java.
Referenced by frontend.SLogoWorkspace.SLogoWorkspace().
Turtle frontend.SLogoWorkspace.myInitialTurtle private
Definition at line 67 of file SLogoWorkspace.java.
TurtleMover frontend.SLogoWorkspace.myMover private
Definition at line 68 of file SLogoWorkspace.java.
Referenced by frontend.SLogoWorkspace.SLogoWorkspace().
PaneUpdater frontend.SLogoWorkspace.myPaneUpdater private
Definition at line 77 of file SLogoWorkspace.java.
Referenced by frontend.SLogoWorkspace.SLogoWorkspace().
Group frontend.SLogoWorkspace.myRoot = new Group() private
Definition at line 64 of file SLogoWorkspace.java.
TabPane frontend.SLogoWorkspace.myTabPane private
Definition at line 70 of file SLogoWorkspace.java.
Referenced by frontend.SLogoWorkspace.SLogoWorkspace().
Translator frontend.SLogoWorkspace.myTranslator private
Definition at line 71 of file SLogoWorkspace.java.
Referenced by frontend.SLogoWorkspace.SLogoWorkspace().
TurtleCollection frontend.SLogoWorkspace.myTurtleCollection private
Definition at line 73 of file SLogoWorkspace.java.
Referenced by frontend.SLogoWorkspace.SLogoWorkspace().
double frontend.SLogoWorkspace.myWidth private
Definition at line 62 of file SLogoWorkspace.java.
final int frontend.SLogoWorkspace.PANE_HEIGHT = 100 static private
Definition at line 57 of file SLogoWorkspace.java.
final int frontend.SLogoWorkspace.PANE_WIDTH = 200 static private
Definition at line 58 of file SLogoWorkspace.java.
List<GUIFeature> frontend.SLogoWorkspace.startingFeatures private
Definition at line 69 of file SLogoWorkspace.java.
final int frontend.SLogoWorkspace.TEXT_BOX_WIDTH = 100 static private
Definition at line 59 of file SLogoWorkspace.java.
Referenced by frontend.SLogoWorkspace.SLogoWorkspace().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team07/repository/src/frontend/SLogoWorkspace.java