slogo_team07: frontend.Translator Class Reference
frontend.Translator Class Reference
Public Member Functions
Translator (String resourceString)
Translator ()
String translate (String s)
void setLanguage (String s)
Static Public Attributes
static final String DEFAULT_BUNDLE = "resources.languages/" + GUI_PREFERENCES.getString("StartingLanguage")
Private Member Functions
String translateOne (String s)
void setUpDictionary ()
Private Attributes
ResourceBundle myLanguage
Map< String, String > myDictionary
Static Private Attributes
static final String START_TO_BUNDLE = "resources.languages/"
Detailed Description
This class represents a translator to translate entered SLogo commands into English, the language that the parser recognizes.
Author
Chris Bernt
Safkat Islam
Definition at line 17 of file Translator.java.
Constructor & Destructor Documentation
frontend.Translator.Translator (String resourceString)
Constructor.
Parameters
resourceString The String representing the resource bundle to be the language.
Definition at line 31 of file Translator.java.
References frontend.Translator.setUpDictionary().
frontend.Translator.Translator ()
Constructor that uses the default bundle.
Definition at line 39 of file Translator.java.
References frontend.Translator.DEFAULT_BUNDLE.
Member Function Documentation
void frontend.Translator.setLanguage (String s)
Sets the language resource bundle.
Parameters
s The String representing the resource bundle language to be set.
Definition at line 94 of file Translator.java.
References frontend.Translator.setUpDictionary().
Referenced by frontend.ConcreteFeatures.ChangeCodingLanguage.doDropDownClickAction().
void frontend.Translator.setUpDictionary () private
Sets up the dictionary that allows translation. Essentially inverts the map given by the resource bundle so that the other language commands are the keys and the English translations used by the parser are the values.
Definition at line 79 of file Translator.java.
Referenced by frontend.Translator.setLanguage(), and frontend.Translator.Translator().
String frontend.Translator.translate (String s)
This method takes in a string, splits it by whitespace, translates each element, and concatenates it together and returns it.
Parameters
s The String to translate.
Returns
The translated String according the the language resource bundle.
Definition at line 50 of file Translator.java.
References frontend.Translator.translateOne().
Referenced by SLogoControllers.InputController.giveInput().
String frontend.Translator.translateOne (String s) private
Translates one command based on the resource bundle.
Parameters
s The String to translate, which is one translateable command.
Returns
The translated String.
Definition at line 65 of file Translator.java.
Referenced by frontend.Translator.translate().
Member Data Documentation
final String frontend.Translator.DEFAULT_BUNDLE = "resources.languages/" + GUI_PREFERENCES.getString("StartingLanguage") static
Definition at line 19 of file Translator.java.
Referenced by frontend.Translator.Translator().
Map<String, String> frontend.Translator.myDictionary private
Definition at line 24 of file Translator.java.
ResourceBundle frontend.Translator.myLanguage private
Definition at line 22 of file Translator.java.
final String frontend.Translator.START_TO_BUNDLE = "resources.languages/" static private
Definition at line 20 of file Translator.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team07/repository/src/frontend/Translator.java