slogo_team07: turtleClasses.TurtleMover Class Reference
turtleClasses.TurtleMover Class Reference
Public Member Functions
TurtleMover (TurtleCollection turtleCollection)
void startDrawing (List< ExpressionNode > instructions)
Private Attributes
TurtleCollection myTurtleCollection
Detailed Description
This class has the ability to read commands to call them on turtles.
Author
Chris Bernt
Safkat Islam
Definition at line 16 of file TurtleMover.java.
Constructor & Destructor Documentation
turtleClasses.TurtleMover.TurtleMover (TurtleCollection turtleCollection)
Constructor.
Parameters
turtleCollection The collection of turtles on which to run the commands.
Definition at line 25 of file TurtleMover.java.
Member Function Documentation
void turtleClasses.TurtleMover.startDrawing (List< ExpressionNode > instructions)
Runs the list of commands on the turtles.
Parameters
instructions List of commands to execute.
Definition at line 34 of file TurtleMover.java.
References turtleClasses.TurtleCollection.getLastActiveTurtle(), turtleClasses.TurtleSnapshot.getTurtleSnapshot(), turtleClasses.TurtleCollection.setActiveTurtles(), and turtleClasses.TurtleSnapshot.update().
Referenced by frontend.ConcreteFeatures.CommandExecuter.action(), frontend.ConcreteFeatures.LoadSLogoFile.action(), and turtleClasses.TurtleKeyHandler.handle().
Member Data Documentation
TurtleCollection turtleClasses.TurtleMover.myTurtleCollection private
Definition at line 18 of file TurtleMover.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team07/repository/src/turtleClasses/TurtleMover.java