slogo_team07: expressionTree.UserFunctionMap Class Reference
expressionTree.UserFunctionMap Class Reference
Public Member Functions
ExpressionNode getFunction (String s)
boolean contains (String s)
void addFunction (String identifier, ListNode commands)
void discardFunction (String identifier)
Set< String > keySet ()
void applyLoadedMap (UserFunctionMap loadedMap)
Static Public Member Functions
static UserFunctionMap getUserFunctionMap ()
Private Member Functions
UserFunctionMap ()
Private Attributes
Map< String, ListNode > userFunctionMap
Static Private Attributes
static final long serialVersionUID = 1897103858901701660L
static UserFunctionMap myUserFunctionMap = new UserFunctionMap()
Detailed Description
Class that holds all user-defined functions. Contains Map variable that maps String identifier for each function to a ListNode.
Class follows Singleton pattern as there should only be one map ever initialized, and several classes on the backend require access to the map.
Class implements Serializable so that it can be written to a file using FileOutputStream, then read to enable save/load of user defined functions.
Author
Mike Zhu
Definition at line 19 of file UserFunctionMap.java.
Constructor & Destructor Documentation
expressionTree.UserFunctionMap.UserFunctionMap () private
Definition at line 30 of file UserFunctionMap.java.
Member Function Documentation
void expressionTree.UserFunctionMap.addFunction (String identifier, ListNode commands)
Definition at line 46 of file UserFunctionMap.java.
Referenced by controlStructures.MakeUserInstruction.evaluate().
void expressionTree.UserFunctionMap.applyLoadedMap (UserFunctionMap loadedMap)
Definition at line 60 of file UserFunctionMap.java.
Referenced by save.load.CustomReaderWriter.readFromFile().
boolean expressionTree.UserFunctionMap.contains (String s)
Definition at line 38 of file UserFunctionMap.java.
Referenced by expressionTree.ExpressionNodeFactory.unrecognizedCommandHandler().
void expressionTree.UserFunctionMap.discardFunction (String identifier)
Definition at line 52 of file UserFunctionMap.java.
ExpressionNode expressionTree.UserFunctionMap.getFunction (String s)
Definition at line 34 of file UserFunctionMap.java.
Referenced by expressionTree.ExpressionNodeFactory.unrecognizedCommandHandler().
static UserFunctionMap expressionTree.UserFunctionMap.getUserFunctionMap () static
Definition at line 42 of file UserFunctionMap.java.
References expressionTree.UserFunctionMap.myUserFunctionMap.
Referenced by controlStructures.MakeUserInstruction.evaluate(), save.load.CustomReaderWriter.readFromFile(), frontend.ConcreteFeatures.CommandsWindow.updatePane(), and save.load.CustomReaderWriter.writeToFile().
Set<String> expressionTree.UserFunctionMap.keySet ()
Definition at line 56 of file UserFunctionMap.java.
Referenced by frontend.ConcreteFeatures.CommandsWindow.updatePane().
Member Data Documentation
UserFunctionMap expressionTree.UserFunctionMap.myUserFunctionMap = new UserFunctionMap() static private
Definition at line 28 of file UserFunctionMap.java.
Referenced by expressionTree.UserFunctionMap.getUserFunctionMap().
final long expressionTree.UserFunctionMap.serialVersionUID = 1897103858901701660L static private
Definition at line 24 of file UserFunctionMap.java.
Map<String, ListNode> expressionTree.UserFunctionMap.userFunctionMap private
Definition at line 26 of file UserFunctionMap.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team07/repository/src/expressionTree/UserFunctionMap.java