slogo_team07: frontend.Pen Class Reference
frontend.Pen Class Reference
Public Member Functions
Pen (Color initColor, double initWidth, boolean initIsDown, String initStyle)
Pen ()
void drawLine (Point2D p1, Point2D p2, Pane holder)
void setLineColor (Color c)
void setLineWidth (double width)
void setLineStyle (String style)
void penUp ()
void penDown ()
boolean isPenDown ()
Static Public Attributes
static final Color DEFAULT_LINE_COLOR = Color.web(GUI_PREFERENCES.getString("LineColor"))
static final double DEFAULT_LINE_WIDTH = Double.parseDouble(GUI_PREFERENCES.getString("LineWidth"))
static final String DEFAULT_LINE_STYLE = GUI_PREFERENCES.getString("LineStyle")
Private Attributes
Color myLineColor
double myLineWidth
String myLineStyle
boolean myIsPenDown
Static Private Attributes
static final Map< String, Double > LINE_STYLES
Detailed Description
This class represents a pen which contains information about the color, style, and width and has the ability to directly draw on a canvas.
Author
Chris Bernt
Safkat Islam
Definition at line 21 of file Pen.java.
Constructor & Destructor Documentation
frontend.Pen.Pen (Color initColor, double initWidth, boolean initIsDown, String initStyle)
Constructor.
Parameters
initColor The initial color of the pen.
initWidth The initial width of the pen.
initIsDown The initial value of whether the pen is down.
initStyle The initial style value of the pen.
Definition at line 51 of file Pen.java.
References frontend.Pen.DEFAULT_LINE_STYLE.
frontend.Pen.Pen ()
Constructor.
Default pen constructor.
Definition at line 72 of file Pen.java.
References frontend.Pen.DEFAULT_LINE_COLOR, frontend.Pen.DEFAULT_LINE_STYLE, and frontend.Pen.DEFAULT_LINE_WIDTH.
Member Function Documentation
void frontend.Pen.drawLine (Point2D p1, Point2D p2, Pane holder)
This draws a line between two points given.
Parameters
p1 The Point2D object of the turtle (the starting point of the line).
p2 The Point2D object of the ending point of the line.
Definition at line 83 of file Pen.java.
Referenced by frontend.LineDrawer.makeLine().
boolean frontend.Pen.isPenDown ()
Checks whether the pen is down.
Returns
Whether the pen is down.
Definition at line 140 of file Pen.java.
References frontend.Pen.myIsPenDown.
Referenced by turtleClasses.TurtleSnapshot.update().
void frontend.Pen.penDown ()
Sets the pen up.
Definition at line 132 of file Pen.java.
Referenced by displayCommands.PenDown.doAction().
void frontend.Pen.penUp ()
Sets the pen down.
Definition at line 125 of file Pen.java.
Referenced by displayCommands.PenUp.doAction().
void frontend.Pen.setLineColor (Color c)
Set the pen color.
Parameters
c Color to be set.
Definition at line 99 of file Pen.java.
Referenced by frontend.ConcreteFeatures.Reset.action(), and displayCommands.SetPenColor.doAction().
void frontend.Pen.setLineStyle (String style)
Sets the style of the pen.
Parameters
style Style of the pen.
Definition at line 118 of file Pen.java.
Referenced by frontend.ConcreteFeatures.Reset.action(), and frontend.ConcreteFeatures.ChooseLineStyle.doAction().
void frontend.Pen.setLineWidth (double width)
Set the pen width.
Parameters
width The width of the pen.
Definition at line 108 of file Pen.java.
Referenced by frontend.ConcreteFeatures.Reset.action(), and displayCommands.SetPenSize.doAction().
Member Data Documentation
final Color frontend.Pen.DEFAULT_LINE_COLOR = Color.web(GUI_PREFERENCES.getString("LineColor")) static
Definition at line 38 of file Pen.java.
Referenced by frontend.Pen.Pen().
final String frontend.Pen.DEFAULT_LINE_STYLE = GUI_PREFERENCES.getString("LineStyle") static
Definition at line 40 of file Pen.java.
Referenced by frontend.Pen.Pen().
final double frontend.Pen.DEFAULT_LINE_WIDTH = Double.parseDouble(GUI_PREFERENCES.getString("LineWidth")) static
Definition at line 39 of file Pen.java.
Referenced by frontend.Pen.Pen().
final Map<String, Double> frontend.Pen.LINE_STYLES static private
Initial value:
= new HashMap<String, Double>()
            {
                private static final long serialVersionUID = 1L;
            {
                put("Dotted", 3d);
                put("Dashed", 10d);
                put("Solid", Double.MAX_VALUE);
            }}
Definition at line 27 of file Pen.java.
boolean frontend.Pen.myIsPenDown private
Definition at line 26 of file Pen.java.
Referenced by frontend.Pen.isPenDown().
Color frontend.Pen.myLineColor private
Definition at line 23 of file Pen.java.
String frontend.Pen.myLineStyle private
Definition at line 25 of file Pen.java.
double frontend.Pen.myLineWidth private
Definition at line 24 of file Pen.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team07/repository/src/frontend/Pen.java