slogo_team07: controlStructures.MakeUserInstruction Class Reference
controlStructures.MakeUserInstruction Class Reference
Public Member Functions
MakeUserInstruction ()
double evaluate ()
void setChildren (Stack< ExpressionNode > childStack)
Public Member Functions inherited from expressionTree.ExpressionNode
ExpressionNode ()
ExpressionNode (int numChild)
abstract double evaluate ()
List< DisplayNode > makeInstructionList ()
void setValue (double a)
double getValue ()
void setChildren (Stack< ExpressionNode > childStack)
Private Attributes
UnrecognizedFunction myFunction
ListNode myVariables
ListNode myCommands
Additional Inherited Members
Protected Member Functions inherited from expressionTree.ExpressionNode
ExpressionNode getLeft ()
ExpressionNode getRight ()
void setLeft (ExpressionNode toSet)
void setRight (ExpressionNode toSet)
int getNumChildren ()
Protected Attributes inherited from expressionTree.ExpressionNode
double myValue
ExpressionNode myRight
ExpressionNode myLeft
int numChildren
List< DisplayNode > instructionList
Detailed Description
Used when the user wants to define custom functions. Depends on the ListNode class (for defining commands within brackets []) and of course the UserFunctionMap class, in which user defined functions and their String identifiers are stored.
Author
Mike Zhu
Definition at line 17 of file MakeUserInstruction.java.
Constructor & Destructor Documentation
controlStructures.MakeUserInstruction.MakeUserInstruction ()
Definition at line 24 of file MakeUserInstruction.java.
Member Function Documentation
double controlStructures.MakeUserInstruction.evaluate ()
Definition at line 29 of file MakeUserInstruction.java.
References expressionTree.UserFunctionMap.addFunction(), expressionTree.ListNode.evaluate(), expressionTree.UnrecognizedFunction.getIdentifier(), expressionTree.UserFunctionMap.getUserFunctionMap(), and controlStructures.MakeUserInstruction.myCommands.
void controlStructures.MakeUserInstruction.setChildren (Stack< ExpressionNode > childStack)
Definition at line 40 of file MakeUserInstruction.java.
References expressionTree.ExpressionNode.numChildren.
Member Data Documentation
ListNode controlStructures.MakeUserInstruction.myCommands private
Definition at line 21 of file MakeUserInstruction.java.
Referenced by controlStructures.MakeUserInstruction.evaluate().
UnrecognizedFunction controlStructures.MakeUserInstruction.myFunction private
Definition at line 19 of file MakeUserInstruction.java.
ListNode controlStructures.MakeUserInstruction.myVariables private
Definition at line 20 of file MakeUserInstruction.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team07/repository/src/controlStructures/MakeUserInstruction.java