slogo_team07: expressionTree.ExpressionTreeBuilder Class Reference
expressionTree.ExpressionTreeBuilder Class Reference
Public Member Functions
ExpressionTreeBuilder (String s)
List< DisplayNode > getOutputList ()
List< ExpressionNode > getAllNodes ()
Private Member Functions
void getTree (Stack< ExpressionNode > processNodes)
Private Attributes
ExpressionNodeFactory nodeGetter
List< DisplayNode > outputList
List< ExpressionNode > nodeList
Detailed Description
Definition at line 22 of file ExpressionTreeBuilder.java.
Constructor & Destructor Documentation
expressionTree.ExpressionTreeBuilder.ExpressionTreeBuilder (String s)
Definition at line 29 of file ExpressionTreeBuilder.java.
References expressionTree.ExpressionNodeFactory.getAllNodes(), and expressionTree.ExpressionTreeBuilder.getTree().
Member Function Documentation
List<ExpressionNode> expressionTree.ExpressionTreeBuilder.getAllNodes ()
Definition at line 70 of file ExpressionTreeBuilder.java.
References expressionTree.ExpressionTreeBuilder.nodeList.
Referenced by expressionTree.ListNode.evaluate().
List<DisplayNode> expressionTree.ExpressionTreeBuilder.getOutputList ()
Definition at line 66 of file ExpressionTreeBuilder.java.
References expressionTree.ExpressionTreeBuilder.outputList.
Referenced by expressionTree.ListNode.evaluate(), and backend.Parser.parse().
void expressionTree.ExpressionTreeBuilder.getTree (Stack< ExpressionNode > processNodes) private
Parameters
processNodes
Definition at line 47 of file ExpressionTreeBuilder.java.
References expressionTree.ExpressionNode.evaluate(), and expressionTree.ExpressionNode.setChildren().
Referenced by expressionTree.ExpressionTreeBuilder.ExpressionTreeBuilder().
Member Data Documentation
ExpressionNodeFactory expressionTree.ExpressionTreeBuilder.nodeGetter private
Definition at line 24 of file ExpressionTreeBuilder.java.
List<ExpressionNode> expressionTree.ExpressionTreeBuilder.nodeList private
Definition at line 27 of file ExpressionTreeBuilder.java.
Referenced by expressionTree.ExpressionTreeBuilder.getAllNodes().
List<DisplayNode> expressionTree.ExpressionTreeBuilder.outputList private
Definition at line 26 of file ExpressionTreeBuilder.java.
Referenced by expressionTree.ExpressionTreeBuilder.getOutputList().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team07/repository/src/expressionTree/ExpressionTreeBuilder.java