slogo_team07: turtleClasses.Turtle Class Reference
turtleClasses.Turtle Class Reference
Public Member Functions
Turtle (double startX, double startY, String startImage, Canvas canvas, int id)
Turtle (Canvas canvas, int id)
double move (double value)
double rotate (double value)
void handleActiveOutline ()
void changeImage (String newImage)
void stamp ()
void setDirection (double dir)
double getDirection ()
void goToCoord (double x, double y)
void resetPosition ()
void resetImage ()
void showTurtle ()
void hideTurtle ()
Pen getPen ()
boolean isShowing ()
double getX ()
double getY ()
boolean getIsActive ()
void setActive (boolean active)
int getID ()
Static Public Attributes
static final double DEGREES_TO_RADIANS_FACTOR = Math.PI / 180
static final double IMAGE_WIDTH = 30
static final double IMAGE_HEIGHT = 30
static final String TURTLE_DEFAULT_IMAGE = "arrow_red.png"
static final int TURTLE_DEFAULT_DIRECTION = 90
Private Member Functions
void toggleActive ()
void handleDirection ()
Private Attributes
double myX
double myY
double myDirection
ImageView myImage
HBox myContainer
Canvas myCanvas
Pen myPen
boolean myShowTurtle
double myInitX
double myInitY
String myInitImage
LineDrawer myDrawer
boolean isActive
int myID
Static Private Attributes
static final String IMAGE_DIRECTORY = "../images/"
static final String BORDER_RED = "-fx-border-color: red;"
static final String BORDER_SOLID = "-fx-border-style: solid;"
static final String BORDER_WIDTH = "-fx-border-width: 2;"
static final String BORDER_GREEN = "-fx-border-color: green;"
static final int TURTLE_DEFAULT_Y = CANVAS_HEIGHT/2
static final int TURTLE_DEFAULT_X = CANVAS_WIDTH/2
Detailed Description
This class represents the turtle object, handling the data and the graphical rendering. We chose to not separate this class into frontend and backend since each turtle object would need one of each. See BothTurtle for a prototype of how the refactored class would have looked. We did not think the new design was any better.
Author
Chris Bernt
Safkat Islam
Definition at line 27 of file Turtle.java.
Constructor & Destructor Documentation
turtleClasses.Turtle.Turtle (double startX, double startY, String startImage, Canvas canvas, int id)
Constructor
Parameters
startX The initial X-Coordinate of the turtle
startY The initial Y-Coordinate of the turtle
startImage The initial image of the turtle, represented by a string
canvas The canvas this turtle is placed on
id The ID of this turtle
Definition at line 66 of file Turtle.java.
References turtleClasses.Turtle.handleActiveOutline(), turtleClasses.Turtle.toggleActive(), and turtleClasses.Turtle.TURTLE_DEFAULT_DIRECTION.
turtleClasses.Turtle.Turtle (Canvas canvas, int id)
Shortened Constructor
Parameters
canvas The canvas the turtle is placed on
id The ID of the turtle
Definition at line 112 of file Turtle.java.
References turtleClasses.Turtle.TURTLE_DEFAULT_IMAGE, turtleClasses.Turtle.TURTLE_DEFAULT_X, and turtleClasses.Turtle.TURTLE_DEFAULT_Y.
Member Function Documentation
void turtleClasses.Turtle.changeImage (String newImage)
Changes the turtle's image.
Parameters
newImage The String representing the new image
Definition at line 196 of file Turtle.java.
Referenced by displayCommands.SetShape.doAction(), frontend.ConcreteFeatures.ChooseImage.doAction(), and turtleClasses.Turtle.resetImage().
double turtleClasses.Turtle.getDirection ()
Returns
The turtle's current heading/direction.
Definition at line 225 of file Turtle.java.
References turtleClasses.Turtle.myDirection.
Referenced by frontend.LineDrawer.LineDrawer(), and turtleClasses.TurtleSnapshot.update().
int turtleClasses.Turtle.getID ()
Returns
The turtle's ID
Definition at line 319 of file Turtle.java.
References turtleClasses.Turtle.myID.
Referenced by turtleClasses.TurtleCollection.setActiveTurtles(), turtleClasses.TurtleCollection.TurtleCollection(), and turtleClasses.TurtleSnapshot.update().
boolean turtleClasses.Turtle.getIsActive ()
Returns
Whether the turtle is active.
Definition at line 303 of file Turtle.java.
References turtleClasses.Turtle.isActive.
Referenced by turtleClasses.TurtleCollection.checkAndAddActiveTurtle(), and turtleClasses.Turtle.toggleActive().
Pen turtleClasses.Turtle.getPen ()
Returns
The turtle's pen.
Definition at line 275 of file Turtle.java.
References turtleClasses.Turtle.myPen.
Referenced by displayCommands.SetPenSize.doAction(), displayCommands.PenUp.doAction(), displayCommands.SetPenColor.doAction(), displayCommands.PenDown.doAction(), frontend.ConcreteFeatures.ChooseLineStyle.doAction(), frontend.LineDrawer.LineDrawer(), and turtleClasses.TurtleSnapshot.update().
double turtleClasses.Turtle.getX ()
Returns
The X-Coordinate of the turtle.
Definition at line 289 of file Turtle.java.
References turtleClasses.Turtle.myX.
Referenced by frontend.LineDrawer.LineDrawer(), and turtleClasses.TurtleSnapshot.update().
double turtleClasses.Turtle.getY ()
Returns
The Y-Coordinate of the turtle.
Definition at line 296 of file Turtle.java.
References turtleClasses.Turtle.myY.
Referenced by frontend.LineDrawer.LineDrawer(), and turtleClasses.TurtleSnapshot.update().
void turtleClasses.Turtle.goToCoord (double x, double y)
Sets the turtle's location.
Parameters
x X-Coordinate of new location
y Y-Coordinate of new Location
Definition at line 234 of file Turtle.java.
Referenced by turtleClasses.Turtle.resetPosition().
void turtleClasses.Turtle.handleActiveOutline ()
Adds the correct border around a turtle based on activeness.
Definition at line 180 of file Turtle.java.
References turtleClasses.Turtle.BORDER_SOLID.
Referenced by turtleClasses.Turtle.setActive(), turtleClasses.Turtle.toggleActive(), and turtleClasses.Turtle.Turtle().
void turtleClasses.Turtle.handleDirection () private
Helper method to make sure direction is always within 0-360 degrees
Definition at line 169 of file Turtle.java.
Referenced by turtleClasses.Turtle.rotate(), and turtleClasses.Turtle.setDirection().
void turtleClasses.Turtle.hideTurtle ()
Makes the turtle's image not displayed on the canvas.
Definition at line 267 of file Turtle.java.
Referenced by displayCommands.HideTurtle.doAction().
boolean turtleClasses.Turtle.isShowing ()
Returns
Whether the turtle's image is being displayed on the canvas.
Definition at line 282 of file Turtle.java.
References turtleClasses.Turtle.myShowTurtle.
Referenced by turtleClasses.TurtleSnapshot.update().
double turtleClasses.Turtle.move (double value)
This method handles linear turtle motion.
Parameters
value The amount this turtle should move forward.
Returns
The amount moved
Definition at line 130 of file Turtle.java.
References frontend.LineDrawer.draw().
Referenced by displayCommands.Backward.doAction(), and displayCommands.Forward.doAction().
void turtleClasses.Turtle.resetImage ()
Sets turtle's image to its initial image.
Definition at line 252 of file Turtle.java.
References turtleClasses.Turtle.changeImage().
void turtleClasses.Turtle.resetPosition ()
Sets turtle's position to its initial position.
Definition at line 245 of file Turtle.java.
References turtleClasses.Turtle.goToCoord().
Referenced by displayCommands.Home.doAction(), and displayCommands.ClearScreen.doAction().
double turtleClasses.Turtle.rotate (double value)
This method handles turtle rotation.
Parameters
value The number of degrees to rotate left.
Returns
The degrees turned
Definition at line 155 of file Turtle.java.
References turtleClasses.Turtle.handleDirection().
Referenced by displayCommands.Left.doAction(), and displayCommands.Right.doAction().
void turtleClasses.Turtle.setActive (boolean active)
Sets the turtle's activeness.
Parameters
active Whether the turtle is active
Definition at line 311 of file Turtle.java.
References turtleClasses.Turtle.handleActiveOutline().
Referenced by turtleClasses.TurtleCollection.setActiveTurtles(), and turtleClasses.Turtle.toggleActive().
void turtleClasses.Turtle.setDirection (double dir)
Sets the turtle's heading/direction.
Parameters
dir The direction to face.
Definition at line 216 of file Turtle.java.
References turtleClasses.Turtle.handleDirection().
Referenced by displayCommands.SetTowards.doAction().
void turtleClasses.Turtle.showTurtle ()
Makes the turtle's image displayed on the canvas.
Definition at line 259 of file Turtle.java.
Referenced by displayCommands.ShowTurtle.doAction().
void turtleClasses.Turtle.stamp ()
Places a stamp of the turtle on the canvas.
Definition at line 205 of file Turtle.java.
Referenced by displayCommands.Stamp.doAction().
void turtleClasses.Turtle.toggleActive () private
Toggles whether this turtle is active or not.
Definition at line 119 of file Turtle.java.
References turtleClasses.Turtle.getIsActive(), turtleClasses.Turtle.handleActiveOutline(), and turtleClasses.Turtle.setActive().
Referenced by turtleClasses.Turtle.Turtle().
Member Data Documentation
final String turtleClasses.Turtle.BORDER_GREEN = "-fx-border-color: green;" static private
Definition at line 33 of file Turtle.java.
final String turtleClasses.Turtle.BORDER_RED = "-fx-border-color: red;" static private
Definition at line 30 of file Turtle.java.
final String turtleClasses.Turtle.BORDER_SOLID = "-fx-border-style: solid;" static private
Definition at line 31 of file Turtle.java.
Referenced by turtleClasses.Turtle.handleActiveOutline().
final String turtleClasses.Turtle.BORDER_WIDTH = "-fx-border-width: 2;" static private
Definition at line 32 of file Turtle.java.
final double turtleClasses.Turtle.DEGREES_TO_RADIANS_FACTOR = Math.PI / 180 static
Definition at line 34 of file Turtle.java.
final String turtleClasses.Turtle.IMAGE_DIRECTORY = "../images/" static private
Definition at line 29 of file Turtle.java.
final double turtleClasses.Turtle.IMAGE_HEIGHT = 30 static
Definition at line 36 of file Turtle.java.
final double turtleClasses.Turtle.IMAGE_WIDTH = 30 static
Definition at line 35 of file Turtle.java.
boolean turtleClasses.Turtle.isActive private
Definition at line 54 of file Turtle.java.
Referenced by turtleClasses.Turtle.getIsActive().
Canvas turtleClasses.Turtle.myCanvas private
Definition at line 47 of file Turtle.java.
HBox turtleClasses.Turtle.myContainer private
Definition at line 46 of file Turtle.java.
double turtleClasses.Turtle.myDirection private
Definition at line 44 of file Turtle.java.
Referenced by turtleClasses.Turtle.getDirection().
LineDrawer turtleClasses.Turtle.myDrawer private
Definition at line 53 of file Turtle.java.
int turtleClasses.Turtle.myID private
Definition at line 55 of file Turtle.java.
Referenced by turtleClasses.Turtle.getID().
ImageView turtleClasses.Turtle.myImage private
Definition at line 45 of file Turtle.java.
String turtleClasses.Turtle.myInitImage private
Definition at line 52 of file Turtle.java.
double turtleClasses.Turtle.myInitX private
Definition at line 50 of file Turtle.java.
double turtleClasses.Turtle.myInitY private
Definition at line 51 of file Turtle.java.
Pen turtleClasses.Turtle.myPen private
Definition at line 48 of file Turtle.java.
Referenced by turtleClasses.Turtle.getPen().
boolean turtleClasses.Turtle.myShowTurtle private
Definition at line 49 of file Turtle.java.
Referenced by turtleClasses.Turtle.isShowing().
double turtleClasses.Turtle.myX private
Definition at line 42 of file Turtle.java.
Referenced by turtleClasses.Turtle.getX().
double turtleClasses.Turtle.myY private
Definition at line 43 of file Turtle.java.
Referenced by turtleClasses.Turtle.getY().
final int turtleClasses.Turtle.TURTLE_DEFAULT_DIRECTION = 90 static
Definition at line 40 of file Turtle.java.
Referenced by turtleClasses.Turtle.Turtle().
final String turtleClasses.Turtle.TURTLE_DEFAULT_IMAGE = "arrow_red.png" static
Definition at line 37 of file Turtle.java.
Referenced by turtleClasses.Turtle.Turtle().
final int turtleClasses.Turtle.TURTLE_DEFAULT_X = CANVAS_WIDTH/2 static private
Definition at line 39 of file Turtle.java.
Referenced by turtleClasses.Turtle.Turtle().
final int turtleClasses.Turtle.TURTLE_DEFAULT_Y = CANVAS_HEIGHT/2 static private
Definition at line 38 of file Turtle.java.
Referenced by turtleClasses.Turtle.Turtle().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team07/repository/src/turtleClasses/Turtle.java