slogo_team07: displayCommands.Tell Class Reference
displayCommands.Tell Class Reference
Public Member Functions
Tell ()
void doAction (TurtleCollection turtles)
double evaluate ()
List< DisplayNode > makeInstructionList ()
Public Member Functions inherited from displayCommands.DisplayNode
DisplayNode (int i)
String toString ()
void doAction (TurtleCollection turtles)
Public Member Functions inherited from expressionTree.ExpressionNode
ExpressionNode ()
ExpressionNode (int numChild)
abstract double evaluate ()
List< DisplayNode > makeInstructionList ()
void setValue (double a)
double getValue ()
void setChildren (Stack< ExpressionNode > childStack)
Protected Member Functions
void doAction (Turtle turtle)
Protected Member Functions inherited from displayCommands.DisplayNode
abstract void doAction (Turtle turtle)
Protected Member Functions inherited from expressionTree.ExpressionNode
ExpressionNode getLeft ()
ExpressionNode getRight ()
void setLeft (ExpressionNode toSet)
void setRight (ExpressionNode toSet)
int getNumChildren ()
Private Attributes
List< Double > toTell
Additional Inherited Members
Protected Attributes inherited from expressionTree.ExpressionNode
double myValue
ExpressionNode myRight
ExpressionNode myLeft
int numChildren
List< DisplayNode > instructionList
Static Protected Attributes inherited from displayCommands.DisplayNode
static final int ONE = 1
static final int ZERO = 0
Detailed Description
Definition at line 11 of file Tell.java.
Constructor & Destructor Documentation
displayCommands.Tell.Tell ()
Definition at line 14 of file Tell.java.
Member Function Documentation
void displayCommands.Tell.doAction (TurtleCollection turtles)
Definition at line 21 of file Tell.java.
References turtleClasses.TurtleCollection.setActiveTurtles().
void displayCommands.Tell.doAction (Turtle turtle) protected
Definition at line 52 of file Tell.java.
double displayCommands.Tell.evaluate ()
Definition at line 32 of file Tell.java.
References expressionTree.ExpressionNode.evaluate(), expressionTree.ExpressionNode.getLeft(), expressionTree.ListNode.getListContents(), expressionTree.ExpressionNode.myLeft, and expressionTree.ExpressionNode.myValue.
List<DisplayNode> displayCommands.Tell.makeInstructionList ()
Definition at line 44 of file Tell.java.
References expressionTree.ExpressionNode.instructionList.
Member Data Documentation
List<Double> displayCommands.Tell.toTell private
Definition at line 13 of file Tell.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team07/repository/src/displayCommands/Tell.java