slogo_team07: frontend.ConcreteFeatures.Reset Class Reference
frontend.ConcreteFeatures.Reset Class Reference
Public Member Functions
Reset (double x, double y, String buttonName, Canvas canvas, TurtleCollection turtles, PaneUpdater pu)
void action ()
Public Member Functions inherited from frontend.ConcreteFeatures.ClearCanvas
ClearCanvas (double x, double y, String buttonName, Canvas canvas)
void action ()
Public Member Functions inherited from frontend.AbstractFeatures.SLogoButton
SLogoButton (double x, double y, String buttonName)
abstract void action ()
Group makeTool ()
Public Member Functions inherited from frontend.AbstractFeatures.GUIFeature
GUIFeature (double x, double y)
abstract void action ()
abstract Group makeTool ()
Private Attributes
TurtleCollection myTurtleCollection
PaneUpdater myPaneUpdater
Additional Inherited Members
Static Public Attributes inherited from frontend.AbstractFeatures.SLogoButton
static final int BUTTON_WIDTH = 200
static final int BUTTON_HEIGHT = 25
Protected Attributes inherited from frontend.ConcreteFeatures.ClearCanvas
Canvas myCanvas
Protected Attributes inherited from frontend.AbstractFeatures.GUIFeature
double myX
double myY
Detailed Description
This class represents a button that allows the user to reset the workspace, moving all turtles back home and removing all lines and stamps and reverting line/color/background to their initial states.
Author
Chris Bernt
Safkat Islam
Definition at line 23 of file Reset.java.
Constructor & Destructor Documentation
frontend.ConcreteFeatures.Reset.Reset (double x, double y, String buttonName, Canvas canvas, TurtleCollection turtles, PaneUpdater pu)
Constructor
See also
ClearCanvas::ClearCanvasButton(double, double, String, Canvas)
Parameters
turtles Turtles to be reset.
pu PaneUpdater to update based on the reset.
Definition at line 35 of file Reset.java.
Member Function Documentation
void frontend.ConcreteFeatures.Reset.action ()
Resets all aspects of the current workspace to the default: clears the canvas/background, sets turtle to initial position facing up, Sets turtle to initial image, sets line color to black and line width to 1,
Definition at line 50 of file Reset.java.
References turtleClasses.TurtleCollection.setActiveTurtles(), frontend.Pen.setLineColor(), frontend.Pen.setLineStyle(), frontend.Pen.setLineWidth(), and frontend.PaneUpdater.updateAll().
Member Data Documentation
PaneUpdater frontend.ConcreteFeatures.Reset.myPaneUpdater private
Definition at line 26 of file Reset.java.
TurtleCollection frontend.ConcreteFeatures.Reset.myTurtleCollection private
Definition at line 25 of file Reset.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team07/repository/src/frontend/ConcreteFeatures/Reset.java