slogo_team07: expressionTree.ExpressionNodeFactory Class Reference
expressionTree.ExpressionNodeFactory Class Reference
Public Member Functions
Stack< ExpressionNode > getAllNodes (String s)
ExpressionNode variableHandler (String s)
Private Member Functions
ExpressionNode getNode (String s)
ExpressionNode commandHandler (String command) throws InstantiationException, IllegalAccessException
ExpressionNode unrecognizedCommandHandler (String command)
Private Attributes
VariableNodeMap myVariables = VariableNodeMap.getVariableNodeMap()
UserFunctionMap myUserFunctions = UserFunctionMap.getUserFunctionMap()
boolean makingFunction = false
String[] myPackages
Detailed Description
Class called by ExpressionTreeBuilder that takes in a String representing user-input Slogo code, returns a set of ExpressionNodes used to build the tree.
Contains code to parse two special cases: 1) Left and right brackets indicating sections of code used in Repeat and user-defined functions 2) Variables identified by a colon, e.g. :b
ExpressionNode objects are created using reflection. Throws up error window when unrecognized commands are entered.
Author
Mike Zhu
Definition at line 23 of file ExpressionNodeFactory.java.
Member Function Documentation
ExpressionNode expressionTree.ExpressionNodeFactory.commandHandler (String command) throws InstantiationException, IllegalAccessException private
Uses reflection to create an ExpressionNode object based on input String.
Unrecognized commands return a UnrecognizedFunction object that effectively a blank null object. Whether or not an error popup is then thrown depends on whether the unrecognized command followed the MakeUserInstruction command (for which the function name must not be defined).
Parameters
command
Returns
Exceptions
InstantiationException
IllegalAccessException
Definition at line 109 of file ExpressionNodeFactory.java.
References expressionTree.ExpressionNodeFactory.unrecognizedCommandHandler().
Referenced by expressionTree.ExpressionNodeFactory.getNode().
Stack<ExpressionNode> expressionTree.ExpressionNodeFactory.getAllNodes (String s)
Definition at line 39 of file ExpressionNodeFactory.java.
References expressionTree.ListNode.add(), and expressionTree.ExpressionNodeFactory.getNode().
Referenced by expressionTree.ExpressionTreeBuilder.ExpressionTreeBuilder().
ExpressionNode expressionTree.ExpressionNodeFactory.getNode (String s) private
Definition at line 70 of file ExpressionNodeFactory.java.
References expressionTree.ExpressionNodeFactory.commandHandler(), expressionTree.ExpressionNode.setValue(), and expressionTree.ExpressionNodeFactory.variableHandler().
Referenced by expressionTree.ExpressionNodeFactory.getAllNodes().
ExpressionNode expressionTree.ExpressionNodeFactory.unrecognizedCommandHandler (String command) private
Definition at line 141 of file ExpressionNodeFactory.java.
References expressionTree.UserFunctionMap.contains(), and expressionTree.UserFunctionMap.getFunction().
Referenced by expressionTree.ExpressionNodeFactory.commandHandler().
ExpressionNode expressionTree.ExpressionNodeFactory.variableHandler (String s)
Definition at line 137 of file ExpressionNodeFactory.java.
References expressionTree.VariableNodeMap.getVariable().
Referenced by expressionTree.ExpressionNodeFactory.getNode().
Member Data Documentation
boolean expressionTree.ExpressionNodeFactory.makingFunction = false private
Definition at line 27 of file ExpressionNodeFactory.java.
String [] expressionTree.ExpressionNodeFactory.myPackages private
Initial value:
= { "commandAbstractClasses",
            "comparators",
            "controlStructures",
            "displayCommands",
            "expressionTree",
            "mathOperations",
            "multipleTurtleCommands",
            "turtleQueries"}
Definition at line 29 of file ExpressionNodeFactory.java.
UserFunctionMap expressionTree.ExpressionNodeFactory.myUserFunctions = UserFunctionMap.getUserFunctionMap() private
Definition at line 26 of file ExpressionNodeFactory.java.
VariableNodeMap expressionTree.ExpressionNodeFactory.myVariables = VariableNodeMap.getVariableNodeMap() private
Definition at line 25 of file ExpressionNodeFactory.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team07/repository/src/expressionTree/ExpressionNodeFactory.java