slogo_team07: turtleClasses.TurtleCollection Class Reference
turtleClasses.TurtleCollection Class Reference
Public Member Functions
TurtleCollection (List< Turtle > turtles, Canvas canvas)
Turtle getLastActiveTurtle () throws SLogoException
void addTurtle (Turtle t)
void setActiveTurtles (List< Integer > turtles)
void setActiveTurtles ()
Iterator< Turtle > iterator ()
SLogoCanvas getCanvas ()
Private Member Functions
void checkAndAddActiveTurtle (Turtle t)
Private Attributes
Map< Integer, Turtle > myTurtles
List< Turtle > myActiveTurtles
Canvas myCanvas
Detailed Description
A class representing a wrapper for a collection of turtles. Only allows specific things to be done, including iterating over it, adding a turtle, and setting new turtles.
Author
Chris Bernt
Safkat Islam
Definition at line 24 of file TurtleCollection.java.
Constructor & Destructor Documentation
turtleClasses.TurtleCollection.TurtleCollection (List< Turtle > turtles, Canvas canvas)
Constructor. Also sets up the turtles map and active turtles list.
Parameters
turtles The initial list of turtles to be in this collection.
canvas The canvas the turtles are added to.
Definition at line 36 of file TurtleCollection.java.
References turtleClasses.TurtleCollection.checkAndAddActiveTurtle(), and turtleClasses.Turtle.getID().
Member Function Documentation
void turtleClasses.TurtleCollection.addTurtle (Turtle t)
Adds a turtle to the turtle map and to the active list if it is active.
Parameters
t The turtle to be added.
Definition at line 74 of file TurtleCollection.java.
References turtleClasses.TurtleCollection.checkAndAddActiveTurtle().
Referenced by frontend.SLogoWorkspace.SLogoWorkspace().
void turtleClasses.TurtleCollection.checkAndAddActiveTurtle (Turtle t) private
Parameters
t
Definition at line 82 of file TurtleCollection.java.
References turtleClasses.Turtle.getIsActive().
Referenced by turtleClasses.TurtleCollection.addTurtle(), turtleClasses.TurtleCollection.setActiveTurtles(), and turtleClasses.TurtleCollection.TurtleCollection().
SLogoCanvas turtleClasses.TurtleCollection.getCanvas ()
Gets the canvas turtles are added to.
Returns
The canvas turtles are added to.
Definition at line 157 of file TurtleCollection.java.
References turtleClasses.TurtleCollection.myCanvas.
Referenced by displayCommands.SetBackground.doAction(), displayCommands.ClearObjects.doAction(), and displayCommands.SetPenColor.doAction().
Turtle turtleClasses.TurtleCollection.getLastActiveTurtle () throws SLogoException
Gets the last active turtle for queries. Throws a SLogoException is there are no active turtles.
Returns
The last active turtle.
Definition at line 54 of file TurtleCollection.java.
Referenced by turtleClasses.TurtleMover.startDrawing().
Iterator<Turtle> turtleClasses.TurtleCollection.iterator ()
Iterator that iterates only the active turtles.
Definition at line 134 of file TurtleCollection.java.
void turtleClasses.TurtleCollection.setActiveTurtles (List< Integer > turtles)
Takes a list of turtles and makes these, and only these, active. Used with Tell.
Parameters
turtles List of turtles to be added as active.
Definition at line 95 of file TurtleCollection.java.
References turtleClasses.Turtle.getID(), and turtleClasses.Turtle.setActive().
Referenced by frontend.ConcreteFeatures.SetLineColor.action(), frontend.ConcreteFeatures.ChangeLineWidth.action(), frontend.ConcreteFeatures.Reset.action(), displayCommands.Tell.doAction(), displayCommands.Ask.doAction(), frontend.ConcreteFeatures.TurtleChanger.doDropDownClickAction(), turtleClasses.TurtleMover.startDrawing(), and frontend.ConcreteFeatures.TurtleStatsWindow.updatePane().
void turtleClasses.TurtleCollection.setActiveTurtles ()
Manually sets the active turtle list based on the current turtle map. Used after a user clicks on turtles to toggle their activeness.
Definition at line 123 of file TurtleCollection.java.
References turtleClasses.TurtleCollection.checkAndAddActiveTurtle().
Member Data Documentation
List<Turtle> turtleClasses.TurtleCollection.myActiveTurtles private
Definition at line 27 of file TurtleCollection.java.
Canvas turtleClasses.TurtleCollection.myCanvas private
Definition at line 28 of file TurtleCollection.java.
Referenced by turtleClasses.TurtleCollection.getCanvas().
Map<Integer, Turtle> turtleClasses.TurtleCollection.myTurtles private
Definition at line 26 of file TurtleCollection.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team07/repository/src/turtleClasses/TurtleCollection.java