slogo_team07: frontend.ConcreteFeatures.LoadSLogoFile Class Reference
frontend.ConcreteFeatures.LoadSLogoFile Class Reference
Public Member Functions
LoadSLogoFile (double x, double y, String buttonName, TurtleMover mover, PaneUpdater pu, Translator t)
void action ()
Public Member Functions inherited from frontend.AbstractFeatures.SLogoButton
SLogoButton (double x, double y, String buttonName)
abstract void action ()
Group makeTool ()
Public Member Functions inherited from frontend.AbstractFeatures.GUIFeature
GUIFeature (double x, double y)
abstract void action ()
abstract Group makeTool ()
Private Attributes
PaneUpdater myPaneUpdater
TurtleMover myMover
Translator myTranslator
Additional Inherited Members
Static Public Attributes inherited from frontend.AbstractFeatures.SLogoButton
static final int BUTTON_WIDTH = 200
static final int BUTTON_HEIGHT = 25
Protected Attributes inherited from frontend.AbstractFeatures.GUIFeature
double myX
double myY
Detailed Description
This class represents a button that allows the user to open a logo file from a folder and run it.
Author
Chris Bernt
Safkat Islam
Definition at line 25 of file LoadSLogoFile.java.
Constructor & Destructor Documentation
frontend.ConcreteFeatures.LoadSLogoFile.LoadSLogoFile (double x, double y, String buttonName, TurtleMover mover, PaneUpdater pu, Translator t)
See also
SLogoButton::GUIFeatureWithButton(double, double, String)
Parameters
mover The TurtleMover to run the commands.
pu The PaneUpdater to update the panes based on the file's commands.
t The Translator to translate the text file.
Definition at line 38 of file LoadSLogoFile.java.
Member Function Documentation
void frontend.ConcreteFeatures.LoadSLogoFile.action ()
When the button is clicked, create a new FileChooser with an extension filter to .logo. Get the chosen file and run it like a normal input. Throws a SLogoException if the file cannot be found.
Definition at line 53 of file LoadSLogoFile.java.
References SLogoControllers.InputController.getInstructions(), SLogoControllers.InputController.giveInput(), turtleClasses.TurtleMover.startDrawing(), and frontend.PaneUpdater.updateAll().
Member Data Documentation
TurtleMover frontend.ConcreteFeatures.LoadSLogoFile.myMover private
Definition at line 28 of file LoadSLogoFile.java.
PaneUpdater frontend.ConcreteFeatures.LoadSLogoFile.myPaneUpdater private
Definition at line 27 of file LoadSLogoFile.java.
Translator frontend.ConcreteFeatures.LoadSLogoFile.myTranslator private
Definition at line 29 of file LoadSLogoFile.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team07/repository/src/frontend/ConcreteFeatures/LoadSLogoFile.java