slogo_team07: SLogoControllers.InputController Class Reference
SLogoControllers.InputController Class Reference
Public Member Functions
InputController (Translator t)
InputController ()
void giveInput (String s)
List< ExpressionNode > getInstructions ()
Package Attributes
String input
Private Attributes
Parser parser = new Parser()
Translator myTranslator
Detailed Description
Definition at line 11 of file InputController.java.
Constructor & Destructor Documentation
SLogoControllers.InputController.InputController (Translator t)
Definition at line 16 of file InputController.java.
SLogoControllers.InputController.InputController ()
Definition at line 20 of file InputController.java.
Member Function Documentation
List<ExpressionNode> SLogoControllers.InputController.getInstructions ()
Definition at line 29 of file InputController.java.
References backend.Parser.parse().
Referenced by frontend.ConcreteFeatures.CommandExecuter.action(), frontend.ConcreteFeatures.LoadSLogoFile.action(), and turtleClasses.TurtleKeyHandler.handle().
void SLogoControllers.InputController.giveInput (String s)
Definition at line 24 of file InputController.java.
References frontend.Translator.translate().
Referenced by frontend.ConcreteFeatures.CommandExecuter.action(), frontend.ConcreteFeatures.LoadSLogoFile.action(), and turtleClasses.TurtleKeyHandler.handle().
Member Data Documentation
String SLogoControllers.InputController.input package
Definition at line 13 of file InputController.java.
Translator SLogoControllers.InputController.myTranslator private
Definition at line 14 of file InputController.java.
Parser SLogoControllers.InputController.parser = new Parser() private
Definition at line 12 of file InputController.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team07/repository/src/SLogoControllers/InputController.java