slogo_team07: frontend.ConcreteFeatures.CommandExecuter Class Reference
frontend.ConcreteFeatures.CommandExecuter Class Reference
Public Member Functions
CommandExecuter (double x, double y, double width, double height, TurtleMover mover, String buttonName, String initialText, PaneUpdater pu, Translator t, HistoryCollection history)
void action ()
Public Member Functions inherited from frontend.AbstractFeatures.SLogoTextBox
SLogoTextBox (double x, double y, double width, double height, String buttonName, String initialText)
abstract void action ()
Group makeTool ()
Public Member Functions inherited from frontend.AbstractFeatures.GUIFeature
GUIFeature (double x, double y)
abstract void action ()
abstract Group makeTool ()
Private Attributes
TurtleMover myMover
PaneUpdater myPaneUpdater
Translator myTranslator
HistoryCollection myHistory
Additional Inherited Members
Protected Attributes inherited from frontend.AbstractFeatures.SLogoTextBox
TextInputControl inputBox
double myWidth
double myHeight
String myButtonName
String myInitialText
Protected Attributes inherited from frontend.AbstractFeatures.GUIFeature
double myX
double myY
Detailed Description
This class represents a text box with a run button, that, more importantly, delegates the commands off for execution. Since so many GUIFeatures change based on the commands, it requires many objects to run completely.
Author
Chris Bernt
Safkat Islam
Definition at line 22 of file CommandExecuter.java.
Constructor & Destructor Documentation
frontend.ConcreteFeatures.CommandExecuter.CommandExecuter (double x, double y, double width, double height, TurtleMover mover, String buttonName, String initialText, PaneUpdater pu, Translator t, HistoryCollection history)
See also
SLogoTextBox::GUIFeatureWithTextBox(double, double, double, double, String, String)
Parameters
mover The TurtleMover that moves turtles based on the commands.
pu The PaneUpdater that updates panes based on the commands.
t The Translator to translate the commands.
history The History to add the commands to.
Definition at line 38 of file CommandExecuter.java.
References frontend.AbstractFeatures.SLogoTextBox.inputBox.
Member Function Documentation
void frontend.ConcreteFeatures.CommandExecuter.action ()
Runs the commands and updates history and the panes. Throws a SLogoException if the input is null.
Definition at line 53 of file CommandExecuter.java.
References expressionTree.HistoryCollection.add(), SLogoControllers.InputController.getInstructions(), SLogoControllers.InputController.giveInput(), frontend.AbstractFeatures.SLogoTextBox.inputBox, turtleClasses.TurtleMover.startDrawing(), and frontend.PaneUpdater.updateAll().
Member Data Documentation
HistoryCollection frontend.ConcreteFeatures.CommandExecuter.myHistory private
Definition at line 27 of file CommandExecuter.java.
TurtleMover frontend.ConcreteFeatures.CommandExecuter.myMover private
Definition at line 24 of file CommandExecuter.java.
PaneUpdater frontend.ConcreteFeatures.CommandExecuter.myPaneUpdater private
Definition at line 25 of file CommandExecuter.java.
Translator frontend.ConcreteFeatures.CommandExecuter.myTranslator private
Definition at line 26 of file CommandExecuter.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team07/repository/src/frontend/ConcreteFeatures/CommandExecuter.java