slogo_team07: expressionTree.VariableNodeMap Class Reference
expressionTree.VariableNodeMap Class Reference
Public Member Functions
VariableNode getVariable (String variableName)
void discardVariable (String identifier)
Set< String > keySet ()
void applyLoadedMap (VariableNodeMap loadedMap)
Static Public Member Functions
static VariableNodeMap getVariableNodeMap ()
Private Member Functions
VariableNodeMap ()
void addVariable (String identifier)
Private Attributes
Map< String, VariableNode > variableMap
Static Private Attributes
static final long serialVersionUID = 1L
static VariableNodeMap myVariableNodeMap = new VariableNodeMap()
Detailed Description
Class that holds all user-defined variables. Contains Map variable that maps String identifier for each variable to a VariableNode object..
Class follows Singleton pattern as there should only be one map ever initialized, and several classes on the backend require access to user-defined variables.
Class implements Serializable so that it can be written to a file using FileOutputStream, then read to enable save/load of user defined variables.
Author
Mike Zhu
Definition at line 19 of file VariableNodeMap.java.
Constructor & Destructor Documentation
expressionTree.VariableNodeMap.VariableNodeMap () private
Definition at line 27 of file VariableNodeMap.java.
Member Function Documentation
void expressionTree.VariableNodeMap.addVariable (String identifier) private
Definition at line 40 of file VariableNodeMap.java.
Referenced by expressionTree.VariableNodeMap.getVariable().
void expressionTree.VariableNodeMap.applyLoadedMap (VariableNodeMap loadedMap)
Definition at line 54 of file VariableNodeMap.java.
Referenced by save.load.FileWriter.readFromFile(), and save.load.CustomReaderWriter.readFromFile().
void expressionTree.VariableNodeMap.discardVariable (String identifier)
Definition at line 46 of file VariableNodeMap.java.
VariableNode expressionTree.VariableNodeMap.getVariable (String variableName)
Definition at line 31 of file VariableNodeMap.java.
References expressionTree.VariableNodeMap.addVariable().
Referenced by save.load.FileWriter.main(), frontend.ConcreteFeatures.CurrentVariablesWindow.updatePane(), and expressionTree.ExpressionNodeFactory.variableHandler().
static VariableNodeMap expressionTree.VariableNodeMap.getVariableNodeMap () static
Definition at line 36 of file VariableNodeMap.java.
References expressionTree.VariableNodeMap.myVariableNodeMap.
Referenced by save.load.FileWriter.main(), save.load.FileWriter.readFromFile(), save.load.CustomReaderWriter.readFromFile(), frontend.ConcreteFeatures.CurrentVariablesWindow.updatePane(), save.load.FileWriter.writeToFile(), and save.load.CustomReaderWriter.writeToFile().
Set<String> expressionTree.VariableNodeMap.keySet ()
Definition at line 50 of file VariableNodeMap.java.
Referenced by frontend.ConcreteFeatures.CurrentVariablesWindow.updatePane().
Member Data Documentation
VariableNodeMap expressionTree.VariableNodeMap.myVariableNodeMap = new VariableNodeMap() static private
Definition at line 25 of file VariableNodeMap.java.
Referenced by expressionTree.VariableNodeMap.getVariableNodeMap().
final long expressionTree.VariableNodeMap.serialVersionUID = 1L static private
Definition at line 21 of file VariableNodeMap.java.
Map<String, VariableNode> expressionTree.VariableNodeMap.variableMap private
Definition at line 23 of file VariableNodeMap.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team07/repository/src/expressionTree/VariableNodeMap.java